### ISSUE TITLE
Also render views

### ISSUE THREAD

**Issue by dhirschfeld** [endremborza/sqlmermaid#4]
As it says in the title!

**Comment by dhirschfeld** [comment]
I imagine this one may be (slightly) more involved. Happy to take a look as time allows...

**Comment by dhirschfeld** [comment]
Ok, it might be as simple as passing `views=True` to [`MetaData.reflect`](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.MetaData.reflect):

https://github.com/endremborza/sqlmermaid/blob/8d099fcbd7ab11bda560c4207f0ec3c5fdeef460/sqlmermaid.py#L20

**Comment by dhirschfeld** [comment]
I'm actually passing in the metadata directly so that's on me to ensure the views are reflected.

If you pass in a connection string it might be nice to have the option to also render views.

**Comment by endremborza** [comment]
my only possible issue with this is that I don't know what version of sqlalchemy the views kwarg was added to reflect, but apparently it has been there since [at least before 1.0](https://github.com/sqlalchemy/sqlalchemy/blob/f00657fa8a3a484d3a9207c67c0a1d20ab8313bb/lib/sqlalchemy/sql/schema.py#L2897) so this should be fine.

I can add it directly or you can open a new PR if you'd like, I'll release this with the quite change as soon as it is done

**Comment by dhirschfeld** [comment]
Feel free to add this yourself as I might not get to it for a bit...

**Comment by endremborza** [comment]
0.1.4 released with this

**Comment by dhirschfeld** [comment]
Awesome, thanks @endremborza! Sorry I didn't get around to it myself.

I really appreciate this library and think it'll be super handy with the new [Mermaid support in JupyterLab](https://github.com/ipython/ipython/issues/14319#issuecomment-1925721855)
